// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvspxsgzbbfmunkadhcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2c3B4c2d6YmJmbXVua2FkaGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU5ODcsImV4cCI6MjA3Mzg3MTk4N30.W4XH8BPArw5Tk4X4tR7yT5TIrhtMpR5InwEboXL-YXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});